apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-network-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        name: sriov-network-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      serviceAccountName: sriov-network-operator
      priorityClassName: "system-node-critical"
      containers:
        - name: sriov-network-operator
          # Replace this with the built image name
          image: inspurwyd/sriov-operator:kube-ovn
          command:
          - sriov-network-operator
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENABLE_SRIOVNETWORK_CONTROLLER
              value: "false"
            - name: ENABLE_SRIOVIBNETWORK_CONTROLLER
              value: "false"
            - name: ENABLE_SRIOVNETWORKPOOLCONFIG_CONTROLLER
              value: "false"
            - name: OPERATOR_NAME
              value: sriov-network-operator
            - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
              value: inspurwyd/sriov-config-daemon:kube-ovn
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RELEASE_VERSION
              value: 4.3.0
