apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-config-daemon
  namespace: kube-system